# Generated by Django 5.0 on 2024-01-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medonations_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressrelease',
            name='image',
            field=models.ImageField(default='no-image.jpeg', upload_to='press_releases/'),
        ),
    ]
