# Generated by Django 5.0 on 2024-02-18 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medonations_backend', '0003_blog_delete_pressrelease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='date_published',
        ),
        migrations.AddField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
